### ISSUE TITLE
Selecting a file in large directories is too slow

### ISSUE THREAD

**Issue by subhoghoshX** [cockpit-project/cockpit-navigator#298]
I haven't looked into the implementation yet but it seems like a JS/React issue. Instead of going through the whole list of files and re-rendering everything the same except one (with the darker background), probably use a better algorithm?

**Comment by subhoghoshX** [comment]
Maybe related to this:
1. Switching from a large directory to any other directory is also too slow.
2. Typing or pressing backspace in Filter input sometimes takes several seconds for the characters to appear or disappear.

**Comment by jelly** [comment]
Yup, this is indeed a serious issue we noticed we have done some research in this issue https://github.com/cockpit-project/cockpit-navigator/issues/225 and @garrett worked on a better performing HTML version of the view.

I don't think a different algorithm will save us here as it's basically too many DOM elements and event listeners. I've already worked on re-working the code to use one event listener for the whole view but I ended up getting side-tracked with other cleanup.s

**Comment by allisonkarlitskaya** [comment]
I think this is basically a dup of #225.  

@garrett thinks we're going to tackle this by simplifying our layout.  @jelly thinks its on event handlers.  I think we just need to do less rendering (ie: some kind of virtualized/windowed approach).

**Comment by garrett** [comment]
> garrett thinks we're going to tackle this by simplifying our layout

That's just one of _many_ things I said we need to do. I also pointed out the embedded SVG document problem, the event handler problem, and even talked about virtualized views in matrix a while ago (how they could possibly be useful, but not for us, as our height can differ due to long filenames, and how we really shouldn't truncate the filenames — plus, they usually don't work well and are a bit too complex).

https://github.com/cockpit-project/cockpit-navigator/issues/225#issuecomment-1916890279

I also said we need to do all or most all of these things to fix the problem. There's no "one solution". Having a simple layout with a mess of event handlers won't work. Having just one event handler without fixing the layout won't work. Doing everything in JavaScript instead of using native browser technology (HTML + CSS) won't work — throwing more JavaScript at the problem can only make performance worse, not better.

PatternFly doesn't really have a icon grid widget; the cards are a monster, especially when it comes to scaling. And Cockpit's table code is way too complex overall. (I did find some problems in PatternFly's CSS as a result of this and also suggested a fix. They even applied my suggestion! But only for PatternFly 6, not 5 for whatever reasons... so that'll take some time yet for us to benefit.)

The goal behind the HTML view was to have a simple table layout that could be used for both views without having to do anything at all in JavaScript or the DOM (except toggling a class at the top). It would be impossible to be any quicker by using React to change the view, as it's going to modify the DOM.
